// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (admin_id, action, target_id, target_type, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	AdminID    uuid.UUID             `json:"admin_id"`
	Action     string                `json:"action"`
	TargetID   uuid.NullUUID         `json:"target_id"`
	TargetType sql.NullString        `json:"target_type"`
	Details    pqtype.NullRawMessage `json:"details"`
	IpAddress  sql.NullString        `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetID,
		arg.TargetType,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const getAuditLogsByAction = `-- name: GetAuditLogsByAction :many
SELECT id, admin_id, action, target_id, target_type, details, ip_address, created_at FROM audit_log
WHERE action = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAuditLogsByAction(ctx context.Context, action string) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByAction, action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetID,
			&i.TargetType,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByAdmin = `-- name: GetAuditLogsByAdmin :many
SELECT id, admin_id, action, target_id, target_type, details, ip_address, created_at FROM audit_log
WHERE admin_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAuditLogsByAdmin(ctx context.Context, adminID uuid.UUID) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByAdmin, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetID,
			&i.TargetType,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
