// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    sender_id,
    receiver_id,
    product_id,
    content
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, sender_id, receiver_id, product_id, content, is_read, created_at
`

type CreateMessageParams struct {
	SenderID   uuid.UUID `json:"sender_id"`
	ReceiverID uuid.UUID `json:"receiver_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Content    string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.SenderID,
		arg.ReceiverID,
		arg.ProductID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.ProductID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getConversations = `-- name: GetConversations :many
SELECT DISTINCT ON (
    LEAST(m.sender_id::text, m.receiver_id::text) || m.product_id::text
)
    m.id, m.sender_id, m.receiver_id, m.product_id, m.content, m.is_read, m.created_at,
    u.username  AS sender_name,
    p.title     AS product_title,
    p.image_url_1 AS product_image,
    (
        SELECT ou.username FROM users ou
        WHERE ou.id = CASE WHEN m.sender_id = $1 THEN m.receiver_id ELSE m.sender_id END
    ) AS other_user_name,
    (
        SELECT COUNT(*) FROM messages um
        WHERE um.product_id = m.product_id
          AND um.receiver_id = $1
          AND um.sender_id = CASE WHEN m.sender_id = $1 THEN m.receiver_id ELSE m.sender_id END
          AND um.is_read = FALSE
    ) AS unread_count
FROM messages m
JOIN users    u ON u.id = m.sender_id
JOIN products p ON p.id = m.product_id
WHERE m.sender_id = $1
OR    m.receiver_id = $1
ORDER BY
    LEAST(m.sender_id::text, m.receiver_id::text) || m.product_id::text,
    m.created_at DESC
`

type GetConversationsRow struct {
	ID            uuid.UUID `json:"id"`
	SenderID      uuid.UUID `json:"sender_id"`
	ReceiverID    uuid.UUID `json:"receiver_id"`
	ProductID     uuid.UUID `json:"product_id"`
	Content       string    `json:"content"`
	IsRead        bool      `json:"is_read"`
	CreatedAt     time.Time `json:"created_at"`
	SenderName    string    `json:"sender_name"`
	ProductTitle  string    `json:"product_title"`
	ProductImage  string    `json:"product_image"`
	OtherUserName string    `json:"other_user_name"`
	UnreadCount   int64     `json:"unread_count"`
}

func (q *Queries) GetConversations(ctx context.Context, senderID uuid.UUID) ([]GetConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversations, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsRow
	for rows.Next() {
		var i GetConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.ProductID,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.SenderName,
			&i.ProductTitle,
			&i.ProductImage,
			&i.OtherUserName,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT
    m.id, m.sender_id, m.receiver_id, m.product_id, m.content, m.is_read, m.created_at,
    u.username AS sender_name
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE (
    (m.sender_id = $1 AND m.receiver_id = $2)
    OR
    (m.sender_id = $2 AND m.receiver_id = $1)
)
AND m.product_id = $3
ORDER BY m.created_at ASC
`

type GetMessagesByConversationParams struct {
	SenderID   uuid.UUID `json:"sender_id"`
	ReceiverID uuid.UUID `json:"receiver_id"`
	ProductID  uuid.UUID `json:"product_id"`
}

type GetMessagesByConversationRow struct {
	ID         uuid.UUID `json:"id"`
	SenderID   uuid.UUID `json:"sender_id"`
	ReceiverID uuid.UUID `json:"receiver_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Content    string    `json:"content"`
	IsRead     bool      `json:"is_read"`
	CreatedAt  time.Time `json:"created_at"`
	SenderName string    `json:"sender_name"`
}

func (q *Queries) GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]GetMessagesByConversationRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, arg.SenderID, arg.ReceiverID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByConversationRow
	for rows.Next() {
		var i GetMessagesByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.ProductID,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM messages
WHERE receiver_id = $1
AND   is_read     = FALSE
`

func (q *Queries) GetUnreadCount(ctx context.Context, receiverID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCount, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages
SET is_read = TRUE
WHERE product_id  = $1
AND   sender_id   = $2
AND   receiver_id = $3
AND   is_read     = FALSE
`

type MarkMessagesAsReadParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	SenderID   uuid.UUID `json:"sender_id"`
	ReceiverID uuid.UUID `json:"receiver_id"`
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markMessagesAsRead, arg.ProductID, arg.SenderID, arg.ReceiverID)
	return err
}
