// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Admin struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Category struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type EmailQueue struct {
	ID             uuid.UUID             `json:"id"`
	NotificationID uuid.NullUUID         `json:"notification_id"`
	RecipientEmail string                `json:"recipient_email"`
	Subject        string                `json:"subject"`
	TemplateName   string                `json:"template_name"`
	Payload        pqtype.NullRawMessage `json:"payload"`
	Status         sql.NullString        `json:"status"`
	Attempts       sql.NullInt32         `json:"attempts"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	SentAt         sql.NullTime          `json:"sent_at"`
}

type Message struct {
	ID         uuid.UUID `json:"id"`
	SenderID   uuid.UUID `json:"sender_id"`
	ReceiverID uuid.UUID `json:"receiver_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Content    string    `json:"content"`
	IsRead     bool      `json:"is_read"`
	CreatedAt  time.Time `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID             `json:"id"`
	UserID    uuid.UUID             `json:"user_id"`
	Type      string                `json:"type"`
	Title     string                `json:"title"`
	Message   string                `json:"message"`
	IsRead    sql.NullBool          `json:"is_read"`
	CreatedAt sql.NullTime          `json:"created_at"`
	ReadAt    sql.NullTime          `json:"read_at"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	Link      sql.NullString        `json:"link"`
}

type NotificationPreference struct {
	UserID         uuid.UUID    `json:"user_id"`
	EmailMessages  sql.NullBool `json:"email_messages"`
	EmailOffers    sql.NullBool `json:"email_offers"`
	EmailSales     sql.NullBool `json:"email_sales"`
	EmailMarketing sql.NullBool `json:"email_marketing"`
	InappMessages  sql.NullBool `json:"inapp_messages"`
	InappOffers    sql.NullBool `json:"inapp_offers"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type Payment struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
}

type Product struct {
	ID          uuid.UUID `json:"id"`
	SellerID    uuid.UUID `json:"seller_id"`
	CategoryID  int32     `json:"category_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Condition   string    `json:"condition"`
	ImageUrl1   string    `json:"image_url_1"`
	ImageUrl2   string    `json:"image_url_2"`
	ImageUrl3   string    `json:"image_url_3"`
	ImageUrl4   string    `json:"image_url_4"`
}

type Report struct {
	ID         uuid.UUID `json:"id"`
	ReporterID uuid.UUID `json:"reporter_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Reason     string    `json:"reason"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Details    string    `json:"details"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	Username      string    `json:"username"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	IsVerified    bool      `json:"is_verified"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	StudentIDUrl  string    `json:"student_id_url"`
	AccountStatus string    `json:"account_status"`
	PhoneNumber   string    `json:"phone_number"`
	FullName      string    `json:"full_name"`
}
