// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createDefaultNotificationPreferences = `-- name: CreateDefaultNotificationPreferences :one
INSERT INTO notification_preferences (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, email_messages, email_offers, email_sales, email_marketing, inapp_messages, inapp_offers, created_at, updated_at
`

func (q *Queries) CreateDefaultNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, createDefaultNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EmailMessages,
		&i.EmailOffers,
		&i.EmailSales,
		&i.EmailMarketing,
		&i.InappMessages,
		&i.InappOffers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailJob = `-- name: CreateEmailJob :one
INSERT INTO email_queue (notification_id, recipient_email, subject, template_name, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, notification_id, recipient_email, subject, template_name, payload, status, attempts, created_at, sent_at
`

type CreateEmailJobParams struct {
	NotificationID uuid.NullUUID         `json:"notification_id"`
	RecipientEmail string                `json:"recipient_email"`
	Subject        string                `json:"subject"`
	TemplateName   string                `json:"template_name"`
	Payload        pqtype.NullRawMessage `json:"payload"`
}

func (q *Queries) CreateEmailJob(ctx context.Context, arg CreateEmailJobParams) (EmailQueue, error) {
	row := q.db.QueryRowContext(ctx, createEmailJob,
		arg.NotificationID,
		arg.RecipientEmail,
		arg.Subject,
		arg.TemplateName,
		arg.Payload,
	)
	var i EmailQueue
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.RecipientEmail,
		&i.Subject,
		&i.TemplateName,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, message, metadata, link)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, title, message, is_read, created_at, read_at, metadata, link
`

type CreateNotificationParams struct {
	UserID   uuid.UUID             `json:"user_id"`
	Type     string                `json:"type"`
	Title    string                `json:"title"`
	Message  string                `json:"message"`
	Metadata pqtype.NullRawMessage `json:"metadata"`
	Link     sql.NullString        `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Metadata,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
		&i.Metadata,
		&i.Link,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, email_messages, email_offers, email_sales, email_marketing, inapp_messages, inapp_offers, created_at, updated_at FROM notification_preferences
WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EmailMessages,
		&i.EmailOffers,
		&i.EmailSales,
		&i.EmailMarketing,
		&i.InappMessages,
		&i.InappOffers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingEmailJobs = `-- name: GetPendingEmailJobs :many
SELECT id, notification_id, recipient_email, subject, template_name, payload, status, attempts, created_at, sent_at FROM email_queue
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingEmailJobs(ctx context.Context, limit int32) ([]EmailQueue, error) {
	rows, err := q.db.QueryContext(ctx, getPendingEmailJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailQueue
	for rows.Next() {
		var i EmailQueue
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.RecipientEmail,
			&i.Subject,
			&i.TemplateName,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, user_id, type, title, message, is_read, created_at, read_at, metadata, link FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
			&i.ReadAt,
			&i.Metadata,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE, read_at = NOW()
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = TRUE, read_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, title, message, is_read, created_at, read_at, metadata, link
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
		&i.Metadata,
		&i.Link,
	)
	return i, err
}

const updateEmailJobStatus = `-- name: UpdateEmailJobStatus :exec
UPDATE email_queue
SET status = $2, attempts = attempts + 1, sent_at = CASE WHEN $2 = 'sent' THEN NOW() ELSE sent_at END
WHERE id = $1
`

type UpdateEmailJobStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdateEmailJobStatus(ctx context.Context, arg UpdateEmailJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailJobStatus, arg.ID, arg.Status)
	return err
}

const updateNotificationPreferences = `-- name: UpdateNotificationPreferences :one
UPDATE notification_preferences
SET 
    email_messages = $2,
    email_offers = $3,
    email_sales = $4,
    email_marketing = $5,
    inapp_messages = $6,
    inapp_offers = $7,
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, email_messages, email_offers, email_sales, email_marketing, inapp_messages, inapp_offers, created_at, updated_at
`

type UpdateNotificationPreferencesParams struct {
	UserID         uuid.UUID    `json:"user_id"`
	EmailMessages  sql.NullBool `json:"email_messages"`
	EmailOffers    sql.NullBool `json:"email_offers"`
	EmailSales     sql.NullBool `json:"email_sales"`
	EmailMarketing sql.NullBool `json:"email_marketing"`
	InappMessages  sql.NullBool `json:"inapp_messages"`
	InappOffers    sql.NullBool `json:"inapp_offers"`
}

func (q *Queries) UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationPreferences,
		arg.UserID,
		arg.EmailMessages,
		arg.EmailOffers,
		arg.EmailSales,
		arg.EmailMarketing,
		arg.InappMessages,
		arg.InappOffers,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EmailMessages,
		&i.EmailOffers,
		&i.EmailSales,
		&i.EmailMarketing,
		&i.InappMessages,
		&i.InappOffers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
