// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    buyer_id,
    seller_id,
    product_id,
    amount,
    phone_number,
    operator,
    reference
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at
`

type CreatePaymentParams struct {
	BuyerID     uuid.UUID      `json:"buyer_id"`
	SellerID    uuid.UUID      `json:"seller_id"`
	ProductID   uuid.UUID      `json:"product_id"`
	Amount      string         `json:"amount"`
	PhoneNumber string         `json:"phone_number"`
	Operator    string         `json:"operator"`
	Reference   sql.NullString `json:"reference"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.BuyerID,
		arg.SellerID,
		arg.ProductID,
		arg.Amount,
		arg.PhoneNumber,
		arg.Operator,
		arg.Reference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllHeldPayments = `-- name: GetAllHeldPayments :many
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.status = 'held'
ORDER BY p.created_at ASC
`

type GetAllHeldPaymentsRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetAllHeldPayments(ctx context.Context) ([]GetAllHeldPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllHeldPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHeldPaymentsRow
	for rows.Next() {
		var i GetAllHeldPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuyerName,
			&i.SellerName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuyerPayments = `-- name: GetBuyerPayments :many
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.buyer_id = $1
ORDER BY p.created_at DESC
`

type GetBuyerPaymentsRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetBuyerPayments(ctx context.Context, buyerID uuid.UUID) ([]GetBuyerPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBuyerPayments, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBuyerPaymentsRow
	for rows.Next() {
		var i GetBuyerPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuyerName,
			&i.SellerName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.id = $1
`

type GetPaymentByIDRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (GetPaymentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuyerName,
		&i.SellerName,
		&i.ProductTitle,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.reference = $1
`

type GetPaymentByReferenceRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

const hasActivePayment = `-- name: HasActivePayment :one
SELECT EXISTS(
    SELECT 1 FROM payments
    WHERE product_id = $1
      AND ((buyer_id = $2 AND seller_id = $3) OR (seller_id = $2 AND buyer_id = $3))
      AND status IN ('held', 'released')
) AS exists
`

type HasActivePaymentParams struct {
	ProductID uuid.UUID `json:"product_id"`
	UserID1   uuid.UUID `json:"user_id_1"`
	UserID2   uuid.UUID `json:"user_id_2"`
}

func (q *Queries) HasActivePayment(ctx context.Context, arg HasActivePaymentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActivePayment, arg.ProductID, arg.UserID1, arg.UserID2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

func (q *Queries) GetPaymentByReference(ctx context.Context, reference sql.NullString) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuyerName,
		&i.SellerName,
		&i.ProductTitle,
	)
	return i, err
}

const getSellerPayments = `-- name: GetSellerPayments :many
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.seller_id = $1
ORDER BY p.created_at DESC
`

type GetSellerPaymentsRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetSellerPayments(ctx context.Context, sellerID uuid.UUID) ([]GetSellerPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSellerPayments, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSellerPaymentsRow
	for rows.Next() {
		var i GetSellerPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuyerName,
			&i.SellerName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentAfterRelease = `-- name: UpdatePaymentAfterRelease :one
UPDATE payments
SET
    status             = $2,
    platform_fee       = $3,
    net_amount         = $4,
    withdraw_reference = $5,
    receipt_number     = $6,
    receipt_pdf_url    = $7,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at
`

type UpdatePaymentAfterReleaseParams struct {
	ID                uuid.UUID      `json:"id"`
	Status            string         `json:"status"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
}

func (q *Queries) UpdatePaymentAfterRelease(ctx context.Context, arg UpdatePaymentAfterReleaseParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentAfterRelease,
		arg.ID,
		arg.Status,
		arg.PlatformFee,
		arg.NetAmount,
		arg.WithdrawReference,
		arg.ReceiptNumber,
		arg.ReceiptPdfUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentToHeld = `-- name: UpdatePaymentToHeld :one
UPDATE payments
SET
    status     = 'held',
    updated_at = NOW()
WHERE reference = $1
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at
`

func (q *Queries) UpdatePaymentToHeld(ctx context.Context, reference sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentToHeld, reference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
