// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimPaymentForRelease = `-- name: ClaimPaymentForRelease :one
UPDATE payments
SET status     = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'held'
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason
`

type ClaimPaymentForReleaseParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// ClaimPaymentForRelease atomically transitions a payment out of 'held'
// into an in-progress state ($2 = 'releasing' or 'refunding'). Only one
// concurrent caller can succeed; the loser gets sql.ErrNoRows. This guards
// the escrow withdrawal against double-spend.
func (q *Queries) ClaimPaymentForRelease(ctx context.Context, arg ClaimPaymentForReleaseParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, claimPaymentForRelease, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    buyer_id,
    seller_id,
    product_id,
    amount,
    phone_number,
    operator,
    reference
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason
`

type CreatePaymentParams struct {
	BuyerID     uuid.UUID      `json:"buyer_id"`
	SellerID    uuid.UUID      `json:"seller_id"`
	ProductID   uuid.UUID      `json:"product_id"`
	Amount      string         `json:"amount"`
	PhoneNumber string         `json:"phone_number"`
	Operator    string         `json:"operator"`
	Reference   sql.NullString `json:"reference"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.BuyerID,
		arg.SellerID,
		arg.ProductID,
		arg.Amount,
		arg.PhoneNumber,
		arg.Operator,
		arg.Reference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
	)
	return i, err
}

const getAllHeldPayments = `-- name: GetAllHeldPayments :many
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at, p.rejection_reason,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.status = 'held'
ORDER BY p.created_at ASC
LIMIT $2 OFFSET $1
`

type GetAllHeldPaymentsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type GetAllHeldPaymentsRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetAllHeldPayments(ctx context.Context, arg GetAllHeldPaymentsParams) ([]GetAllHeldPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllHeldPayments, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHeldPaymentsRow
	for rows.Next() {
		var i GetAllHeldPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RejectionReason,
			&i.BuyerName,
			&i.SellerName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuyerPayments = `-- name: GetBuyerPayments :many
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at, p.rejection_reason,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.buyer_id = $1
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type GetBuyerPaymentsParams struct {
	BuyerID uuid.UUID `json:"buyer_id"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type GetBuyerPaymentsRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetBuyerPayments(ctx context.Context, arg GetBuyerPaymentsParams) ([]GetBuyerPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBuyerPayments, arg.BuyerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBuyerPaymentsRow
	for rows.Next() {
		var i GetBuyerPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RejectionReason,
			&i.BuyerName,
			&i.SellerName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at, p.rejection_reason,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.id = $1
`

type GetPaymentByIDRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (GetPaymentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
		&i.BuyerName,
		&i.SellerName,
		&i.ProductTitle,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at, p.rejection_reason,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.reference = $1
`

type GetPaymentByReferenceRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetPaymentByReference(ctx context.Context, reference sql.NullString) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
		&i.BuyerName,
		&i.SellerName,
		&i.ProductTitle,
	)
	return i, err
}

const getSellerPayments = `-- name: GetSellerPayments :many
SELECT
    p.id, p.buyer_id, p.seller_id, p.product_id, p.amount, p.platform_fee, p.net_amount, p.phone_number, p.operator, p.reference, p.withdraw_reference, p.status, p.receipt_number, p.receipt_pdf_url, p.created_at, p.updated_at, p.rejection_reason,
    u1.username AS buyer_name,
    u2.username AS seller_name,
    pr.title    AS product_title
FROM payments p
JOIN users    u1 ON u1.id = p.buyer_id
JOIN users    u2 ON u2.id = p.seller_id
JOIN products pr ON pr.id = p.product_id
WHERE p.seller_id = $1
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type GetSellerPaymentsParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Offset   int32     `json:"offset"`
	Limit    int32     `json:"limit"`
}

type GetSellerPaymentsRow struct {
	ID                uuid.UUID      `json:"id"`
	BuyerID           uuid.UUID      `json:"buyer_id"`
	SellerID          uuid.UUID      `json:"seller_id"`
	ProductID         uuid.UUID      `json:"product_id"`
	Amount            string         `json:"amount"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	PhoneNumber       string         `json:"phone_number"`
	Operator          string         `json:"operator"`
	Reference         sql.NullString `json:"reference"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	Status            string         `json:"status"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
	BuyerName         string         `json:"buyer_name"`
	SellerName        string         `json:"seller_name"`
	ProductTitle      string         `json:"product_title"`
}

func (q *Queries) GetSellerPayments(ctx context.Context, arg GetSellerPaymentsParams) ([]GetSellerPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSellerPayments, arg.SellerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSellerPaymentsRow
	for rows.Next() {
		var i GetSellerPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RejectionReason,
			&i.BuyerName,
			&i.SellerName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStalePendingPayments = `-- name: GetStalePendingPayments :many
SELECT id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason FROM payments
WHERE status = 'pending'
  AND created_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) GetStalePendingPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getStalePendingPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RejectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStuckReleasingPayments = `-- name: GetStuckReleasingPayments :many
SELECT id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason FROM payments
WHERE status IN ('releasing', 'refunding')
  AND updated_at < NOW() - INTERVAL '10 minutes'
`

// GetStuckReleasingPayments returns payments that entered an in-progress
// money-movement state ('releasing'/'refunding') but never reached a terminal
// state within the reconciliation window — i.e. a CamPay withdrawal likely
// succeeded while the follow-up DB write was lost to a crash. Surfaced to
// operators for manual follow-up.
func (q *Queries) GetStuckReleasingPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getStuckReleasingPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.ProductID,
			&i.Amount,
			&i.PlatformFee,
			&i.NetAmount,
			&i.PhoneNumber,
			&i.Operator,
			&i.Reference,
			&i.WithdrawReference,
			&i.Status,
			&i.ReceiptNumber,
			&i.ReceiptPdfUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RejectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasActivePayment = `-- name: HasActivePayment :one
SELECT EXISTS(
    SELECT 1 FROM payments
    WHERE product_id = $1
      AND ((buyer_id = $2 AND seller_id = $3) OR (seller_id = $2 AND buyer_id = $3))
      AND status IN ('held', 'released')
) AS exists
`

type HasActivePaymentParams struct {
	ProductID uuid.UUID `json:"product_id"`
	BuyerID   uuid.UUID `json:"buyer_id"`
	SellerID  uuid.UUID `json:"seller_id"`
}

func (q *Queries) HasActivePayment(ctx context.Context, arg HasActivePaymentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActivePayment, arg.ProductID, arg.BuyerID, arg.SellerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revertPaymentToHeld = `-- name: RevertPaymentToHeld :one
UPDATE payments
SET status     = 'held',
    updated_at = NOW()
WHERE id = $1 AND status IN ('releasing', 'refunding')
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason
`

// RevertPaymentToHeld puts a claimed payment back to 'held' when the
// CamPay withdrawal fails, so the buyer can retry.
func (q *Queries) RevertPaymentToHeld(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, revertPaymentToHeld, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
	)
	return i, err
}

const updatePaymentAfterRelease = `-- name: UpdatePaymentAfterRelease :one
UPDATE payments
SET
    status             = $2,
    platform_fee       = $3,
    net_amount         = $4,
    withdraw_reference = $5,
    receipt_number     = $6,
    receipt_pdf_url    = $7,
    rejection_reason   = $8,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason
`

type UpdatePaymentAfterReleaseParams struct {
	ID                uuid.UUID      `json:"id"`
	Status            string         `json:"status"`
	PlatformFee       string         `json:"platform_fee"`
	NetAmount         string         `json:"net_amount"`
	WithdrawReference sql.NullString `json:"withdraw_reference"`
	ReceiptNumber     sql.NullString `json:"receipt_number"`
	ReceiptPdfUrl     sql.NullString `json:"receipt_pdf_url"`
	RejectionReason   sql.NullString `json:"rejection_reason"`
}

func (q *Queries) UpdatePaymentAfterRelease(ctx context.Context, arg UpdatePaymentAfterReleaseParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentAfterRelease,
		arg.ID,
		arg.Status,
		arg.PlatformFee,
		arg.NetAmount,
		arg.WithdrawReference,
		arg.ReceiptNumber,
		arg.ReceiptPdfUrl,
		arg.RejectionReason,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
	)
	return i, err
}

const updatePaymentToHeld = `-- name: UpdatePaymentToHeld :one
UPDATE payments
SET
    status     = 'held',
    updated_at = NOW()
WHERE reference = $1 AND status = 'pending'
RETURNING id, buyer_id, seller_id, product_id, amount, platform_fee, net_amount, phone_number, operator, reference, withdraw_reference, status, receipt_number, receipt_pdf_url, created_at, updated_at, rejection_reason
`

func (q *Queries) UpdatePaymentToHeld(ctx context.Context, reference sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentToHeld, reference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.ProductID,
		&i.Amount,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PhoneNumber,
		&i.Operator,
		&i.Reference,
		&i.WithdrawReference,
		&i.Status,
		&i.ReceiptNumber,
		&i.ReceiptPdfUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RejectionReason,
	)
	return i, err
}
