// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    seller_id,
    category_id,
    title,
    description,
    price,
    image_url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, seller_id, category_id, title, description, price, image_url, status, created_at, updated_at
`

type CreateProductParams struct {
	SellerID    uuid.UUID      `json:"seller_id"`
	CategoryID  int32          `json:"category_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Price       string         `json:"price"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.SellerID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
AND  seller_id = $2
`

type DeleteProductParams struct {
	ID       uuid.UUID `json:"id"`
	SellerID uuid.UUID `json:"seller_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.ID, arg.SellerID)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.image_url, p.status, p.created_at, p.updated_at,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.status = 'available'
ORDER BY p.created_at DESC
`

type GetAllProductsRow struct {
	ID           uuid.UUID      `json:"id"`
	SellerID     uuid.UUID      `json:"seller_id"`
	CategoryID   int32          `json:"category_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Price        string         `json:"price"`
	ImageUrl     sql.NullString `json:"image_url"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	SellerName   string         `json:"seller_name"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT 
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.image_url, p.status, p.created_at, p.updated_at,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.id = $1
`

type GetProductByIDRow struct {
	ID           uuid.UUID      `json:"id"`
	SellerID     uuid.UUID      `json:"seller_id"`
	CategoryID   int32          `json:"category_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Price        string         `json:"price"`
	ImageUrl     sql.NullString `json:"image_url"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	SellerName   string         `json:"seller_name"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.CategoryName,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.image_url, p.status, p.created_at, p.updated_at,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.category_id = $1
AND   p.status = 'available'
ORDER BY p.created_at DESC
`

type GetProductsByCategoryRow struct {
	ID           uuid.UUID      `json:"id"`
	SellerID     uuid.UUID      `json:"seller_id"`
	CategoryID   int32          `json:"category_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Price        string         `json:"price"`
	ImageUrl     sql.NullString `json:"image_url"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	SellerName   string         `json:"seller_name"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetProductsByCategory(ctx context.Context, categoryID int32) ([]GetProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCategoryRow
	for rows.Next() {
		var i GetProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsBySellerID = `-- name: GetProductsBySellerID :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.image_url, p.status, p.created_at, p.updated_at,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.seller_id = $1
ORDER BY p.created_at DESC
`

type GetProductsBySellerIDRow struct {
	ID           uuid.UUID      `json:"id"`
	SellerID     uuid.UUID      `json:"seller_id"`
	CategoryID   int32          `json:"category_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Price        string         `json:"price"`
	ImageUrl     sql.NullString `json:"image_url"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	SellerName   string         `json:"seller_name"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetProductsBySellerID(ctx context.Context, sellerID uuid.UUID) ([]GetProductsBySellerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsBySellerID, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsBySellerIDRow
	for rows.Next() {
		var i GetProductsBySellerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.image_url, p.status, p.created_at, p.updated_at,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.status = 'available'
AND  (
    p.title       ILIKE '%' || $1 || '%'
    OR p.description ILIKE '%' || $1 || '%'
)
ORDER BY p.created_at DESC
`

type SearchProductsRow struct {
	ID           uuid.UUID      `json:"id"`
	SellerID     uuid.UUID      `json:"seller_id"`
	CategoryID   int32          `json:"category_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Price        string         `json:"price"`
	ImageUrl     sql.NullString `json:"image_url"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	SellerName   string         `json:"seller_name"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) SearchProducts(ctx context.Context, dollar_1 sql.NullString) ([]SearchProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    category_id = $2,
    title       = $3,
    description = $4,
    price       = $5,
    image_url   = $6,
    updated_at  = NOW()
WHERE id = $1
AND seller_id = $7
RETURNING id, seller_id, category_id, title, description, price, image_url, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	CategoryID  int32          `json:"category_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Price       string         `json:"price"`
	ImageUrl    sql.NullString `json:"image_url"`
	SellerID    uuid.UUID      `json:"seller_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.ImageUrl,
		arg.SellerID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStatus = `-- name: UpdateProductStatus :one
UPDATE products
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
AND  seller_id = $3
RETURNING id, seller_id, category_id, title, description, price, image_url, status, created_at, updated_at
`

type UpdateProductStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	SellerID uuid.UUID `json:"seller_id"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStatus, arg.ID, arg.Status, arg.SellerID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
