// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimProductForPurchase = `-- name: ClaimProductForPurchase :one
UPDATE products SET status = 'in_escrow', updated_at = NOW()
WHERE id = $1 AND status = 'available'
RETURNING id, seller_id, category_id, title, description, price, status, created_at, updated_at, condition, image_url_1, image_url_2, image_url_3, image_url_4
`

func (q *Queries) ClaimProductForPurchase(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, claimProductForPurchase, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Condition,
		&i.ImageUrl1,
		&i.ImageUrl2,
		&i.ImageUrl3,
		&i.ImageUrl4,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    seller_id,
    category_id,
    title,
    description,
    price,
    condition,
    image_url_1,
    image_url_2,
    image_url_3,
    image_url_4
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, seller_id, category_id, title, description, price, status, created_at, updated_at, condition, image_url_1, image_url_2, image_url_3, image_url_4
`

type CreateProductParams struct {
	SellerID    uuid.UUID `json:"seller_id"`
	CategoryID  int32     `json:"category_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Condition   string    `json:"condition"`
	ImageUrl1   string    `json:"image_url_1"`
	ImageUrl2   string    `json:"image_url_2"`
	ImageUrl3   string    `json:"image_url_3"`
	ImageUrl4   string    `json:"image_url_4"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.SellerID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Condition,
		arg.ImageUrl1,
		arg.ImageUrl2,
		arg.ImageUrl3,
		arg.ImageUrl4,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Condition,
		&i.ImageUrl1,
		&i.ImageUrl2,
		&i.ImageUrl3,
		&i.ImageUrl4,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
AND  seller_id = $2
`

type DeleteProductParams struct {
	ID       uuid.UUID `json:"id"`
	SellerID uuid.UUID `json:"seller_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.ID, arg.SellerID)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.status, p.created_at, p.updated_at, p.condition, p.image_url_1, p.image_url_2, p.image_url_3, p.image_url_4,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.status = 'available'
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $1
`

type GetAllProductsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type GetAllProductsRow struct {
	ID           uuid.UUID `json:"id"`
	SellerID     uuid.UUID `json:"seller_id"`
	CategoryID   int32     `json:"category_id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Price        string    `json:"price"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Condition    string    `json:"condition"`
	ImageUrl1    string    `json:"image_url_1"`
	ImageUrl2    string    `json:"image_url_2"`
	ImageUrl3    string    `json:"image_url_3"`
	ImageUrl4    string    `json:"image_url_4"`
	SellerName   string    `json:"seller_name"`
	CategoryName string    `json:"category_name"`
}

func (q *Queries) GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]GetAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Condition,
			&i.ImageUrl1,
			&i.ImageUrl2,
			&i.ImageUrl3,
			&i.ImageUrl4,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT 
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.status, p.created_at, p.updated_at, p.condition, p.image_url_1, p.image_url_2, p.image_url_3, p.image_url_4,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.id = $1
`

type GetProductByIDRow struct {
	ID           uuid.UUID `json:"id"`
	SellerID     uuid.UUID `json:"seller_id"`
	CategoryID   int32     `json:"category_id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Price        string    `json:"price"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Condition    string    `json:"condition"`
	ImageUrl1    string    `json:"image_url_1"`
	ImageUrl2    string    `json:"image_url_2"`
	ImageUrl3    string    `json:"image_url_3"`
	ImageUrl4    string    `json:"image_url_4"`
	SellerName   string    `json:"seller_name"`
	CategoryName string    `json:"category_name"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Condition,
		&i.ImageUrl1,
		&i.ImageUrl2,
		&i.ImageUrl3,
		&i.ImageUrl4,
		&i.SellerName,
		&i.CategoryName,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.status, p.created_at, p.updated_at, p.condition, p.image_url_1, p.image_url_2, p.image_url_3, p.image_url_4,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.category_id = $1
AND   p.status = 'available'
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type GetProductsByCategoryParams struct {
	CategoryID int32 `json:"category_id"`
	Offset     int32 `json:"offset"`
	Limit      int32 `json:"limit"`
}

type GetProductsByCategoryRow struct {
	ID           uuid.UUID `json:"id"`
	SellerID     uuid.UUID `json:"seller_id"`
	CategoryID   int32     `json:"category_id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Price        string    `json:"price"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Condition    string    `json:"condition"`
	ImageUrl1    string    `json:"image_url_1"`
	ImageUrl2    string    `json:"image_url_2"`
	ImageUrl3    string    `json:"image_url_3"`
	ImageUrl4    string    `json:"image_url_4"`
	SellerName   string    `json:"seller_name"`
	CategoryName string    `json:"category_name"`
}

func (q *Queries) GetProductsByCategory(ctx context.Context, arg GetProductsByCategoryParams) ([]GetProductsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByCategory, arg.CategoryID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCategoryRow
	for rows.Next() {
		var i GetProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Condition,
			&i.ImageUrl1,
			&i.ImageUrl2,
			&i.ImageUrl3,
			&i.ImageUrl4,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsBySellerID = `-- name: GetProductsBySellerID :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.status, p.created_at, p.updated_at, p.condition, p.image_url_1, p.image_url_2, p.image_url_3, p.image_url_4,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.seller_id = $1
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type GetProductsBySellerIDParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Offset   int32     `json:"offset"`
	Limit    int32     `json:"limit"`
}

type GetProductsBySellerIDRow struct {
	ID           uuid.UUID `json:"id"`
	SellerID     uuid.UUID `json:"seller_id"`
	CategoryID   int32     `json:"category_id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Price        string    `json:"price"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Condition    string    `json:"condition"`
	ImageUrl1    string    `json:"image_url_1"`
	ImageUrl2    string    `json:"image_url_2"`
	ImageUrl3    string    `json:"image_url_3"`
	ImageUrl4    string    `json:"image_url_4"`
	SellerName   string    `json:"seller_name"`
	CategoryName string    `json:"category_name"`
}

func (q *Queries) GetProductsBySellerID(ctx context.Context, arg GetProductsBySellerIDParams) ([]GetProductsBySellerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsBySellerID, arg.SellerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsBySellerIDRow
	for rows.Next() {
		var i GetProductsBySellerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Condition,
			&i.ImageUrl1,
			&i.ImageUrl2,
			&i.ImageUrl3,
			&i.ImageUrl4,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.status, p.created_at, p.updated_at, p.condition, p.image_url_1, p.image_url_2, p.image_url_3, p.image_url_4,
    u.username  AS seller_name,
    c.name      AS category_name
FROM products p
JOIN users      u ON u.id = p.seller_id
JOIN categories c ON c.id = p.category_id
WHERE p.status = 'available'
AND  (
    p.title       ILIKE '%' || $1 || '%'
    OR p.description ILIKE '%' || $1 || '%'
)
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type SearchProductsParams struct {
	Keyword sql.NullString `json:"keyword"`
	Offset  int32          `json:"offset"`
	Limit   int32          `json:"limit"`
}

type SearchProductsRow struct {
	ID           uuid.UUID `json:"id"`
	SellerID     uuid.UUID `json:"seller_id"`
	CategoryID   int32     `json:"category_id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Price        string    `json:"price"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Condition    string    `json:"condition"`
	ImageUrl1    string    `json:"image_url_1"`
	ImageUrl2    string    `json:"image_url_2"`
	ImageUrl3    string    `json:"image_url_3"`
	ImageUrl4    string    `json:"image_url_4"`
	SellerName   string    `json:"seller_name"`
	CategoryName string    `json:"category_name"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts, arg.Keyword, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Condition,
			&i.ImageUrl1,
			&i.ImageUrl2,
			&i.ImageUrl3,
			&i.ImageUrl4,
			&i.SellerName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    category_id = $2,
    title       = $3,
    description = $4,
    price       = $5,
    condition   = $6,
    image_url_1 = $7,
    image_url_2 = $8,
    image_url_3 = $9,
    image_url_4 = $10,
    updated_at  = NOW()
WHERE id = $1
AND seller_id = $11
RETURNING id, seller_id, category_id, title, description, price, status, created_at, updated_at, condition, image_url_1, image_url_2, image_url_3, image_url_4
`

type UpdateProductParams struct {
	ID          uuid.UUID `json:"id"`
	CategoryID  int32     `json:"category_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Condition   string    `json:"condition"`
	ImageUrl1   string    `json:"image_url_1"`
	ImageUrl2   string    `json:"image_url_2"`
	ImageUrl3   string    `json:"image_url_3"`
	ImageUrl4   string    `json:"image_url_4"`
	SellerID    uuid.UUID `json:"seller_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Condition,
		arg.ImageUrl1,
		arg.ImageUrl2,
		arg.ImageUrl3,
		arg.ImageUrl4,
		arg.SellerID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Condition,
		&i.ImageUrl1,
		&i.ImageUrl2,
		&i.ImageUrl3,
		&i.ImageUrl4,
	)
	return i, err
}

const updateProductStatus = `-- name: UpdateProductStatus :one
UPDATE products
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
AND  seller_id = $3
RETURNING id, seller_id, category_id, title, description, price, status, created_at, updated_at, condition, image_url_1, image_url_2, image_url_3, image_url_4
`

type UpdateProductStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	SellerID uuid.UUID `json:"seller_id"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStatus, arg.ID, arg.Status, arg.SellerID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Condition,
		&i.ImageUrl1,
		&i.ImageUrl2,
		&i.ImageUrl3,
		&i.ImageUrl4,
	)
	return i, err
}
