// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveUser(ctx context.Context, id uuid.UUID) (User, error)
	BlockUser(ctx context.Context, id uuid.UUID) (User, error)
	CountAdmins(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateDefaultNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	CreateEmailJob(ctx context.Context, arg CreateEmailJobParams) (EmailQueue, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetAllReports(ctx context.Context) ([]GetAllReportsRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetConversations(ctx context.Context, senderID uuid.UUID) ([]GetConversationsRow, error)
	GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]GetMessagesByConversationRow, error)
	GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	GetPendingEmailJobs(ctx context.Context, limit int32) ([]EmailQueue, error)
	GetPendingUsers(ctx context.Context) ([]User, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductsByCategory(ctx context.Context, categoryID int32) ([]GetProductsByCategoryRow, error)
	GetProductsBySellerID(ctx context.Context, sellerID uuid.UUID) ([]GetProductsBySellerIDRow, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (GetReportByIDRow, error)
	GetReportsByReporterID(ctx context.Context, reporterID uuid.UUID) ([]GetReportsByReporterIDRow, error)
	GetReportsByStatus(ctx context.Context, status string) ([]GetReportsByStatusRow, error)
	GetUnreadCount(ctx context.Context, receiverID uuid.UUID) (int64, error)
	GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error
	MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	RejectUser(ctx context.Context, id uuid.UUID) (User, error)
	SearchProducts(ctx context.Context, dollar_1 sql.NullString) ([]SearchProductsRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateEmailJobStatus(ctx context.Context, arg UpdateEmailJobStatusParams) error
	UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (NotificationPreference, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error)
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error)
	UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error)
}

var _ Querier = (*Queries)(nil)
