// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveUser(ctx context.Context, id uuid.UUID) (User, error)
	BlockUser(ctx context.Context, id uuid.UUID) (User, error)
	// ClaimPaymentForRelease atomically transitions a payment out of 'held'
	// into an in-progress state ($2 = 'releasing' or 'refunding'). Only one
	// concurrent caller can succeed; the loser gets sql.ErrNoRows. This guards
	// the escrow withdrawal against double-spend.
	ClaimPaymentForRelease(ctx context.Context, arg ClaimPaymentForReleaseParams) (Payment, error)
	CountAdmins(ctx context.Context) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateDefaultNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	CreateEmailJob(ctx context.Context, arg CreateEmailJobParams) (EmailQueue, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllHeldPayments(ctx context.Context) ([]GetAllHeldPaymentsRow, error)
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetAllReports(ctx context.Context) ([]GetAllReportsRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetBuyerPayments(ctx context.Context, buyerID uuid.UUID) ([]GetBuyerPaymentsRow, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetConversations(ctx context.Context, senderID uuid.UUID) ([]GetConversationsRow, error)
	GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]GetMessagesByConversationRow, error)
	GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (GetPaymentByIDRow, error)
	GetPaymentByReference(ctx context.Context, reference sql.NullString) (GetPaymentByReferenceRow, error)
	GetPendingEmailJobs(ctx context.Context, limit int32) ([]EmailQueue, error)
	GetPendingUsers(ctx context.Context) ([]User, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductsByCategory(ctx context.Context, categoryID int32) ([]GetProductsByCategoryRow, error)
	GetProductsBySellerID(ctx context.Context, sellerID uuid.UUID) ([]GetProductsBySellerIDRow, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (GetReportByIDRow, error)
	GetReportsByReporterID(ctx context.Context, reporterID uuid.UUID) ([]GetReportsByReporterIDRow, error)
	GetReportsByStatus(ctx context.Context, status string) ([]GetReportsByStatusRow, error)
	GetSellerPayments(ctx context.Context, sellerID uuid.UUID) ([]GetSellerPaymentsRow, error)
	GetUnreadCount(ctx context.Context, receiverID uuid.UUID) (int64, error)
	GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	HasActivePayment(ctx context.Context, arg HasActivePaymentParams) (bool, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error
	MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	RejectUser(ctx context.Context, id uuid.UUID) (User, error)
	// RevertPaymentToHeld puts a claimed payment back to 'held' when the
	// CamPay withdrawal fails, so the buyer can retry.
	RevertPaymentToHeld(ctx context.Context, id uuid.UUID) (Payment, error)
	SearchProducts(ctx context.Context, dollar_1 sql.NullString) ([]SearchProductsRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateEmailJobStatus(ctx context.Context, arg UpdateEmailJobStatusParams) error
	UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (NotificationPreference, error)
	UpdatePaymentAfterRelease(ctx context.Context, arg UpdatePaymentAfterReleaseParams) (Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePaymentToHeld(ctx context.Context, reference sql.NullString) (Payment, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error)
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error)
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (User, error)
	UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error)
}

var _ Querier = (*Queries)(nil)
