// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    reporter_id,
    product_id,
    reason
) VALUES (
    $1, $2, $3
)
RETURNING id, reporter_id, product_id, reason, status, created_at, updated_at
`

type CreateReportParams struct {
	ReporterID uuid.UUID `json:"reporter_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Reason     string    `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport, arg.ReporterID, arg.ProductID, arg.Reason)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ProductID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllReports = `-- name: GetAllReports :many
SELECT
    r.id, r.reporter_id, r.product_id, r.reason, r.status, r.created_at, r.updated_at,
    u.username  AS reporter_name,
    p.title     AS product_title
FROM reports r
JOIN users    u ON u.id = r.reporter_id
JOIN products p ON p.id = r.product_id
ORDER BY r.created_at DESC
`

type GetAllReportsRow struct {
	ID           uuid.UUID `json:"id"`
	ReporterID   uuid.UUID `json:"reporter_id"`
	ProductID    uuid.UUID `json:"product_id"`
	Reason       string    `json:"reason"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ReporterName string    `json:"reporter_name"`
	ProductTitle string    `json:"product_title"`
}

func (q *Queries) GetAllReports(ctx context.Context) ([]GetAllReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllReportsRow
	for rows.Next() {
		var i GetAllReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ProductID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportByID = `-- name: GetReportByID :one
SELECT
    r.id, r.reporter_id, r.product_id, r.reason, r.status, r.created_at, r.updated_at,
    u.username  AS reporter_name,
    p.title     AS product_title
FROM reports r
JOIN users    u ON u.id = r.reporter_id
JOIN products p ON p.id = r.product_id
WHERE r.id = $1
`

type GetReportByIDRow struct {
	ID           uuid.UUID `json:"id"`
	ReporterID   uuid.UUID `json:"reporter_id"`
	ProductID    uuid.UUID `json:"product_id"`
	Reason       string    `json:"reason"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ReporterName string    `json:"reporter_name"`
	ProductTitle string    `json:"product_title"`
}

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (GetReportByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, id)
	var i GetReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ProductID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReporterName,
		&i.ProductTitle,
	)
	return i, err
}

const getReportsByReporterID = `-- name: GetReportsByReporterID :many
SELECT
    r.id, r.reporter_id, r.product_id, r.reason, r.status, r.created_at, r.updated_at,
    u.username  AS reporter_name,
    p.title     AS product_title
FROM reports r
JOIN users    u ON u.id = r.reporter_id
JOIN products p ON p.id = r.product_id
WHERE r.reporter_id = $1
ORDER BY r.created_at DESC
`

type GetReportsByReporterIDRow struct {
	ID           uuid.UUID `json:"id"`
	ReporterID   uuid.UUID `json:"reporter_id"`
	ProductID    uuid.UUID `json:"product_id"`
	Reason       string    `json:"reason"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ReporterName string    `json:"reporter_name"`
	ProductTitle string    `json:"product_title"`
}

func (q *Queries) GetReportsByReporterID(ctx context.Context, reporterID uuid.UUID) ([]GetReportsByReporterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportsByReporterID, reporterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByReporterIDRow
	for rows.Next() {
		var i GetReportsByReporterIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ProductID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByStatus = `-- name: GetReportsByStatus :many
SELECT
    r.id, r.reporter_id, r.product_id, r.reason, r.status, r.created_at, r.updated_at,
    u.username  AS reporter_name,
    p.title     AS product_title
FROM reports r
JOIN users    u ON u.id = r.reporter_id
JOIN products p ON p.id = r.product_id
WHERE r.status = $1
ORDER BY r.created_at DESC
`

type GetReportsByStatusRow struct {
	ID           uuid.UUID `json:"id"`
	ReporterID   uuid.UUID `json:"reporter_id"`
	ProductID    uuid.UUID `json:"product_id"`
	Reason       string    `json:"reason"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ReporterName string    `json:"reporter_name"`
	ProductTitle string    `json:"product_title"`
}

func (q *Queries) GetReportsByStatus(ctx context.Context, status string) ([]GetReportsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByStatusRow
	for rows.Next() {
		var i GetReportsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ProductID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterName,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, reporter_id, product_id, reason, status, created_at, updated_at
`

type UpdateReportStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ProductID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
