// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token_blacklist.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const blacklistToken = `-- name: BlacklistToken :exec
INSERT INTO token_blacklist (jti, user_id, expires_at)
VALUES ($1, $2, $3)
`

type BlacklistTokenParams struct {
	Jti       string    `json:"jti"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) BlacklistToken(ctx context.Context, arg BlacklistTokenParams) error {
	_, err := q.db.ExecContext(ctx, blacklistToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredBlacklistedTokens = `-- name: DeleteExpiredBlacklistedTokens :exec
DELETE FROM token_blacklist WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredBlacklistedTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBlacklistedTokens)
	return err
}

const getBlacklistedTokensByUser = `-- name: GetBlacklistedTokensByUser :many
SELECT jti, user_id, expires_at, created_at FROM token_blacklist
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBlacklistedTokensByUser(ctx context.Context, userID uuid.UUID) ([]TokenBlacklist, error) {
	rows, err := q.db.QueryContext(ctx, getBlacklistedTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokenBlacklist
	for rows.Next() {
		var i TokenBlacklist
		if err := rows.Scan(
			&i.Jti,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTokenBlacklisted = `-- name: IsTokenBlacklisted :one
SELECT EXISTS(
    SELECT 1 FROM token_blacklist
    WHERE jti = $1 AND expires_at > NOW()
)
`

func (q *Queries) IsTokenBlacklisted(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTokenBlacklisted, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
