// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const approveUser = `-- name: ApproveUser :one
UPDATE users
SET
    account_status = 'approved',
    is_verified    = TRUE,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name
`

func (q *Queries) ApproveUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, approveUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}

const blockUser = `-- name: BlockUser :one
UPDATE users
SET
    account_status = 'blocked',
    updated_at     = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name
`

func (q *Queries) BlockUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, blockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password_hash,
    full_name,
    student_id_url,
    phone_number,
    account_status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'pending'
)
RETURNING id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
	StudentIDUrl string `json:"student_id_url"`
	PhoneNumber  string `json:"phone_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.StudentIDUrl,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name FROM users
ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentIDUrl,
			&i.AccountStatus,
			&i.PhoneNumber,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingUsers = `-- name: GetPendingUsers :many
SELECT id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name FROM users
WHERE account_status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentIDUrl,
			&i.AccountStatus,
			&i.PhoneNumber,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}

const rejectUser = `-- name: RejectUser :one
UPDATE users
SET
    account_status = 'rejected',
    updated_at     = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name
`

func (q *Queries) RejectUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, rejectUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE users
SET
    phone_number = $2,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name
`

type UpdateUserPhoneParams struct {
	ID          uuid.UUID `json:"id"`
	PhoneNumber string    `json:"phone_number"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPhone, arg.ID, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE users
SET
    is_verified = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, is_verified, created_at, updated_at, student_id_url, account_status, phone_number, full_name
`

type UpdateUserVerificationParams struct {
	ID         uuid.UUID `json:"id"`
	IsVerified bool      `json:"is_verified"`
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserVerification, arg.ID, arg.IsVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentIDUrl,
		&i.AccountStatus,
		&i.PhoneNumber,
		&i.FullName,
	)
	return i, err
}
