// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/categories" | "/admin/login" | "/admin/payments" | "/admin/reports" | "/admin/users" | "/category/[id]" | "/conversations" | "/conversations/[productId]" | "/details/[id]" | "/edit/[id]" | "/login" | "/my-reports" | "/mylistings" | "/notifications" | "/profile" | "/purchases" | "/register" | "/report" | "/sales" | "/sell" | "/sell/details" | "/sell/pricing"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/conversations" | "/sell"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/categories": {}
  "/admin/login": {}
  "/admin/payments": {}
  "/admin/reports": {}
  "/admin/users": {}
  "/category/[id]": { "id": string; }
  "/conversations": {}
  "/conversations/[productId]": { "productId": string; }
  "/details/[id]": { "id": string; }
  "/edit/[id]": { "id": string; }
  "/login": {}
  "/my-reports": {}
  "/mylistings": {}
  "/notifications": {}
  "/profile": {}
  "/purchases": {}
  "/register": {}
  "/report": {}
  "/sales": {}
  "/sell": {}
  "/sell/details": {}
  "/sell/pricing": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/conversations": never
  "/sell": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
