var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/register/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10m6bgr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_103_66r.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bg7xqn._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0100oqz._.js")
R.c("server/chunks/ssr/app_0eh2zdk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_register_page_actions_1op-s-x.js")
R.m(279420)
module.exports=R.m(279420).exports
