var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/category/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1n8b49q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1r6v2cm.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bg7xqn._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0100oqz._.js")
R.c("server/chunks/ssr/app_0eh2zdk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_category_[id]_page_actions_01p8l24.js")
R.m(237141)
module.exports=R.m(237141).exports
